### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by fetmar** [Tangerine-Community/Tangerine-client#10]
Intent

to ensure core functionality is not lost as a result of refactoring

Context

Tangerine suffers from almost no test coverage. Unit tests are difficult or impossible to implement due to tight coupling. End to end tests using Capybara and Selenium have historically been very flaky. Ironically refactoring work is needed in order to make Tangerine testable. Until true unit and integration tests can be implemented a hybrid approach relying on extensive use of fixtures for individual testable features will be used.

Specs
- framework should be able to be run continuously
- should cover no less than 80% of the functions described in the tangerine users manual
- all failures must be critical faults

**Comment by chrisekelley** [comment]
Connected repository to Travis CI, so tests run whenever code is committed. There is now a flag on the main README that shows status of the tests.

**Comment by rjcorwin** [comment]
We have most of this accomplished in 0.1.0. Writing more tests is for another day, but we do have a goal of 10 tests for existing features in 0.2.0 and also a rule that we write tests for things as we fix bugs.
