### ISSUE TITLE
'Consent' subtest prototype:  abort not functional

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#100]
In this subtest type, the 'consent prompt' provides users a 'Yes' / 'No' question about consent of the child/interviewee.  If the user taps 'No', they are asked to confirm.  Tapping 'Confirm' should immediately abort the assessment (bring user to 'Assessment Complete' screen).  

Right now, the 'Confirm' button appears, but does nothing.

**Comment by chrisekelley** [comment]
OK - I see this - noConsent is not finding @parent.abort() and it throws an error and stops. Working on this now.
