### ISSUE TITLE
redirect Android 'back' button in the app

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#103]
The Android 'back' button (back-facing triangle in footer) should be set to return users to the Tangerine homescreen when the app is running.  

In the current branch of Tangerine (3a.0.14-8f555b7), the Android back button functioning the same as the Tangerine icon in the top left of the screen:  it tries to return the user to the main landing page if the user is not already there. If a user is already on the Tangerine landing page (instrument menu showing all assessments), tapping the 'back' button does nothing. 

Currently, the Android back button is returning users to their previous screen (kind of. if you tap it enough, havoc ensues).  It should only attempt to return user to main screen.  Like tapping the Tangerine icon, if a user is inside an assessment, tapping the Android 'back' button should prompt them to confirm that they do want to abort that assessment.

**Comment by chrisekelley** [comment]
I think my latest fixes for the back button help, but we're not 100% there yet.

**Comment by skippskipp** [comment]
Working much better, seems like it's just missing the "Confirm" prompt that would prevent unwanted quits.

**Comment by rjcorwin** [comment]
Putting this in Milestone 0.1.2 because we'll give this more love later.

**Comment by chrisekelley** [comment]
Screenshot of alert when pressing back button while still in a test. Please note that it does not tell the user that the test is unsaved.

![tangerine-back-message](https://cloud.githubusercontent.com/assets/861535/12293142/bdec8c86-b9f1-11e5-8c3b-20359223e97c.png)

**Comment by skippskipp** [comment]
This prompt is good.  We don't want to tell them the assessment is unsaved, as it should be the case that they can still "Resume" it, so while it is incomplete, it should still be saved as partial.  Good reminder to check that even partially completed assessments are also synced from tablets.

**Comment by chrisekelley** [comment]
closed in the build tagged 0.1.3.
