### ISSUE TITLE
custom validation error messages not displaying

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#104]
For survey prototype questions.  If a question type is set as 'open', the 'Custom Validation' fields allow the users to define parameters.  

Coupling those parameters is an option for 'Error Message' text.  In the full EGRA assessment example, there is one question that has an error message (variable == student_age_other).  If this question is triggered and the validation not passed, the error message should display on the screen.  The validation itself appears to be working fine, but the Error Message is not displaying:

student_age_other
Error Message:  Please enter numbers only.  Only numbers less than 6 or greater than 24 are allowed.  Other ages should be selected from the above question.

**Comment by skippskipp** [comment]
For some reason, this works in the sample assessment called 'Skip logic tests', but not in the main example EGRA..

**Comment by chrisekelley** [comment]
This is how it should display, correct?

<img width="715" alt="screen shot 2015-12-01 at 7 51 19 pm" src="https://cloud.githubusercontent.com/assets/861535/11510648/063f1804-9865-11e5-9f78-7ac5ad34590e.png">
