### ISSUE TITLE
fix location of subtest title display on survey subtests

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#105]
For any subtest type, the name of the subtest should display just below the name of the assessment on the screen.  

Currently, for survey subtest types, the subtest title is displaying below the 'Student Dialog' field.  This doesn't seem to happen on other subtest types.

**Comment by chrisekelley** [comment]
I believe this is working correctly now - see this screenshot:

<img width="686" alt="screen shot 2015-12-03 at 5 26 25 pm" src="https://cloud.githubusercontent.com/assets/861535/11566510/1120ebce-99e3-11e5-95df-f93837b6e96f.png">

**Comment by skippskipp** [comment]
I can still see this occurring in some spots.  I see it corrected in most, but not all (see shot below).  One pattern that seems to be emerging with this and other issues is that they are not occurring on the newly created test instruments, but they _are_ occurring in running the larger EGRA that was imported from the Liberia group.  
The subtest title in this shot is the text, "EGMA Task 2. Quantity Discrimination" and it should appear above the Student Dialog field.
![screenshot_2015-12-03-15-20-04](https://cloud.githubusercontent.com/assets/2474753/11573113/8f06f4a4-99d2-11e5-8f46-37a22e63fb4f.png)
