### ISSUE TITLE
custom validation error 'charCodeAt' in survey subtests (only when resumed)

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#107]
Survey subtests throw up this error when they are run in an assessment that has been resumed (i.e.  aborted, re-launched): 

![screenshot_2015-11-24-16-47-50](https://cloud.githubusercontent.com/assets/2474753/11381716/996a64a2-92cb-11e5-9752-56c397917044.png)

Testing instructions:
- See #162

**Comment by chrisekelley** [comment]
I did reproduce this error. I have not worked on resume capability yet. I can work on this tomorrow.

**Comment by chrisekelley** [comment]
I tested this again today and cannot reproduce.
