### ISSUE TITLE
'Linked to grid' setting dysfunctional

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#108]
In main example EGRA, the 'Oral Reading Comprehension' survey subtest is linked to the previous Reading grid.  This relationship should mean that the position of the 'last_attempted' bracket affects the logic of the Reading Comprehension survey, eliminating some survey questions from view as configured.  

Either the link or the logic is not functional, all Comprehension questions are being triggered regardless of "last_attempted" position.

**Comment by chrisekelley** [comment]
Check if the id's were not copied correctly when the assessment was copied. Matt says.

**Comment by chrisekelley** [comment]
I confirm that this is not working as it should.
