### ISSUE TITLE
'Location' subtest prototype data view

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#109]
Not a functional priority, but the current build doesn't incorporate the revised pop-out view that had been done for school selection.  This is the current view:
![screenshot_2015-11-24-16-45-09](https://cloud.githubusercontent.com/assets/2474753/11382155/4c06c054-92ce-11e5-9304-da1250497165.png)

But this is the prior view that we should stick with:
![screenshot_2015-11-24-16-53-55](https://cloud.githubusercontent.com/assets/2474753/11382166/6234198a-92ce-11e5-8326-9db9448be413.png)

Testing instructions:
- Tap the play button on the "01. LTTP2 2015 - Student" Assessment.
- Tap your way to the "School Location" subtest.
- Tap the country selection, select "Bong".
- Tap the district selection, select "Zota".
- You should now see that the remaining categories all now have selections.

**Comment by chrisekelley** [comment]
Is this a bootstrap css issue - i.e. is the mobile target working?

**Comment by rjcorwin** [comment]
Working for me in the current APK.

Build: 3a.0.9-243-g8b70dc0-8b70dc0
Device: Samsung S4 Mini, Android 4.4.2

**Comment by chrisekelley** [comment]
I confirm that this works as expected  

Build: 3a.0.9-243-g8b70dc0-8b70dc0
Device: Nexus 5x, Android 6.0.1

![tangerine-location-list](https://cloud.githubusercontent.com/assets/861535/11938003/45f76f8c-a7dd-11e5-92c4-d3159ee546e0.png)
