### ISSUE TITLE
Display 'Transition Comment' text

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#111]
The 'Transition Comment' is a field which should appear above the 'Next' button on any subtest type.  This field is missing from the current build's subtest display.  

Pull request: https://github.com/Tangerine-Community/Tangerine-client/pull/138

Todo:
- [x] Fix empty forward and back button text.
- [x] Get the current subtest from within the context of the View, not the global App object properties.

Testing instructions:
- Tap the play button for "01. LTTP2 2015 - Student" Assessment
- When you get to the sixth subtest, "EGRA Task 1. Letter Name Knowledge", you should see near the bottom, above the "Next" button, a grey box that says "Good effort!  Let's go on to the next section." That is the transition comment.

**Comment by chrisekelley** [comment]
Need to implement in the subtests

**Comment by rjcorwin** [comment]
Here's where my nose is pointing me...

Looking at `runMar` [route in the router](https://github.com/Tangerine-Community/Tangerine-client/blob/feature/111-display-transition-comment-text/src/js/router.coffee#L403), I see that [AssessmentCompositeView](https://github.com/Tangerine-Community/Tangerine-client/blob/feature/111-display-transition-comment-text/src/js/modules/assessment/AssessmentCompositeView.coffee) is where the action is. That View uses the [AssessmentView.handlebars](https://github.com/Tangerine-Community/Tangerine-client/blob/feature/111-display-transition-comment-text/src/templates/AssessmentView.handlebars) template which prints out the back and next buttons, along with a `transitionComment` above the buttons. 

I'm guessing that the transitionComment is supposed to come from the current subtest and every time the next or back buttons are pushed, AssessmentCompositeView renders itself again and uses that current subtest's transitionComment attribute to populate the AssessmentView.handlebars template. This is getting me to dive deep into AssessmentCompositeView, following the events and trying to chase it down to where the render of the template happens. I haven't yet found that render of the template, there is some kind of disconnect in my understanding here.

**Comment by rjcorwin** [comment]
I have a working sandbox with a test Assessment that has transitionComment set on every subtest. @chrisekelley Lets pair on this.

<img width="1280" alt="screen shot 2015-12-10 at 3 45 54 pm" src="https://cloud.githubusercontent.com/assets/156575/11727993/47e38488-9f55-11e5-8388-1155b664722b.png">

**Comment by chrisekelley** [comment]
I would consider moving the following code in Survey.handlebars to Assessment.handlebars:

```
{{#if enumeratorHelp}}
    <button class='subtest_help command'>{{labels.text.help}}</button>
    <div class='enumerator_help' {{fontStyle}}>{{{enumeratorHelp}}}</div>
{{/if}}
{{#if studentDialog}}
    <div class='student_dialog' {{fontStyle}}>{{{studentDialog}}}</div>
{{/if}}
```

Then see how in AssessmentCompositeViiew tha ui.studentDialog andt ui.transitioncomment are populated:

```
    ui.studentDialog  = if (@model.get("studentDialog")  || "") != "" then "<div class='student_dialog' #{@fontStyle || ""}>#{@model.get 'studentDialog'}</div>" else ""
    ui.transitionComment  = if (@model.get("transitionComment")  || "") != "" then "<div class='student_dialog' #{@fontStyle || ""}>#{@model.get 'transitionComment'}</div> <br>" else ""
```

The code is not used in the marionette version, but see that the @model.get 'transitionComment' and @model.get 'studentDialog' are going to the same div.

So, can we create a listener in AssessmentCompositeView that listens to transitionComment and studentDialog in the child model, and then updates (resets?) the view?

In each of the relevant subtests - for example SurveyRunItemView - do we need to trigger something, or would the listener in the parent take care of business?

Also, see how that each subtest model has a parent field which is the parent View.

I hope this is useful!

**Comment by rjcorwin** [comment]
transitionComment is displaying in some places on the feature branch I'm working on. A couple of todo items still, I added them to the description of this issue.

**Comment by rjcorwin** [comment]
A test for this has been written and marked for review.

**Comment by rjcorwin** [comment]
@chrisekelley I can't find a test with a transition comment in the current build to QA this.

**Comment by rjcorwin** [comment]
@chrisekelley Or rather, I've been unsuccessful at finding an Assessment with a Transition Comment :). Do you know of one? The tests in code depend on a test I edited the JSON for.

**Comment by rjcorwin** [comment]
Confirmed in QA

Build: 3a.0.9-243-g8b70dc0-8b70dc0
Device: Samsung S4 Mini, Android 4.4.2
