### ISSUE TITLE
Resuming an assessment causes 'Perform another assessment' to fail

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#112]
At the end of an assessment, tapping 'Save Result' changes that button into 'Perform another assessment'.  Tapping 'Perform another assessment' should in turn re-launch that same assessment from the beginning.  

This works fine, _unless_ the assessment had been resumed.  If you resume an assessment and then tap 'Perform Another Assessment', errors like this occur (nothing loads on this screen and the user can do nothing but exit):
![screenshot_2015-11-25-14-04-18](https://cloud.githubusercontent.com/assets/2474753/11407384/794ef61e-9380-11e5-9542-0b86e4d4aa92.png)

Testing instructions:
- Tap the play button for the "Test: Resume Assessment" Assessment.
- Tap through to "Pupil Context Interview 2" and then exit the Assessment by tapping the Tangerine icon in the top left of the Application and confirming with "ok".
- Tap the stats button for the "Test: Resume Assessment" Assessment.
- Scroll down to the most recent Assessment results, tap "Details", and then tap "Resume".
- You should now see "Pupil Context Interview 2" Question.

**Comment by rjcorwin** [comment]
I just tested this, I see that the route being called is still `resume` related. I think maybe it shouldn't be and should just be `#runMar/:id`.

**Comment by chrisekelley** [comment]
I think it should more be #runMar/: (assessmentId, resultId)  - we still need to pass the resultId. But I get your point - we can refactor runMar to accomodate a result.

**Comment by rjcorwin** [comment]
Does this work? https://github.com/Tangerine-Community/Tangerine-client/pull/156

**Comment by chrisekelley** [comment]
I made a little tweak in PR #160 - on a normal assessment - without resume - when you click on "Perform another assessment" it would not navigate to the url. I believe this is because the backbone app "thinks" it is still at the same url. I added a timestamp to the querystring and it works.

**Comment by rjcorwin** [comment]
Working for me.

Build: 3a.0.9-243-g8b70dc0-8b70dc0
Device: Samsung S4 Mini, Android 4.4.2
