### ISSUE TITLE
Leaving the app mid-assessment can break app view

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#113]
This looks similar to what was happening before when the Android 'Back' button is used.  

To get the screen below, I long pressed on the screen in the middle of an assessment.  The Android top header appeared (Done / Select All / Copy / Share / Web Search).  Tapping 'Web Search' brings up a web search page, which the user must back out of using the Android 'Back' button, causing this:  
![screenshot_2015-11-25-13-50-12](https://cloud.githubusercontent.com/assets/2474753/11407940/d7cf357a-9383-11e5-8473-061a4be03aa5.png)

**Comment by rjcorwin** [comment]
I'm currently not reproducing this issue. Tested on:
- crossbrowsertesting.com (real tablet) / Nexus 7 / Android 4.2 / Chrome 37
- Mac OS 10.10.5 / Chrome 47.0.2526.73 (64-bit)

I'll test in Android Studio and an APK build. Time to get that set up on my new laptop.
