### ISSUE TITLE
Focus mode dysfunctional

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#114]
In survey subtests, having 'Focus Mode' enabled should result in there being only one question displayed per screen.  This is not functional in the current build. 

Testing instructions:
- Open "FocusMode Test" Assessment
- You should see "Q1 focus" question and no others.
- Select an option for the question and tap the "Next question" button
- You should see "Q2 focus" question and no others.
- Select an option for the question and tap the "Next question" button
- Tap the "Next" button.
- You should see a results screen.

**Comment by chrisekelley** [comment]
PR #148 fixes this issue

**Comment by chrisekelley** [comment]
I created an issue for the next milestone for creating a test for this issue.

**Comment by rjcorwin** [comment]
I think I see this working. Not completely sure because I haven't seen it in action before.

Build: 3a.0.9-243-g8b70dc0-8b70dc0
Device: Samsung S4 Mini, Android 4.4.2
