### ISSUE TITLE
Separate presentation from logic

### ISSUE THREAD

**Issue by fetmar** [Tangerine-Community/Tangerine-client#12]
Intent
- To maximize separation of concerns and maintainability

Context
- Too much functionality is coded in views. These separate concerns need to be pulled out and placed into smaller testable helper classes.

**Comment by chrisekelley** [comment]
Most of this is done already - I have pulled out much of the view html into handlebars templates for the marionette release. Some of the code I opted to keep in javascript for particularly complex layouts - such as grids - and the transition to templates in those cases would involve too much effort and probably create more bugs.
