### ISSUE TITLE
Inconsistencies in Login / Sign Up  responsiveness on app startup

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#125]
Upon app startup, the user should be able to easily toggle between the "Login" and "Sign Up" tabs as needed.  Sometimes, this works fine.  Other times, the user has to tap "Sign Up" several times (2, 3, 5, up to 7 times) to have it respond.  I couldn't find any pattern in this.  I quit the app and restarted it several times.  Sometimes, if you tap "Sign Up", you're then unable to tap "Login" and have that be responsive (usually takes more than a few taps, but sometimes works fine).

**Comment by chrisekelley** [comment]
Need to test on Nexus 7 tablet.

**Comment by rjcorwin** [comment]
I'm unable to produce this one with the following device:
- crossbrowsertesting.com (real tablet) / Nexus 7 / Android 4.2 / Chrome 37

**Comment by skippskipp** [comment]
This seems like it's either been resolved somehow or was device-specific; it's behaving normally now.
