### ISSUE TITLE
integrate Discourse forum

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#130]
set up a page for user forums at tangerinecentral.org  using Discourse
http://blog.discourse.org/2014/02/discourse-installs-for-non-profit-and-education/

**Comment by gmcressman** [comment]
What alternatives (to Discourse) were explored? Was Google Groups considered? Where will Discourse be installed?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.orgmailto:gmc@rti.org | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is whyhttp://emailcharter.org/

**Comment by skippskipp** [comment]
We’ve looked mostly over Zendesk’s forum feature and Google Groups, which we used earlier this year during a multi-country data collection.  Discourse sits in the middle of these two price-wise (Zendesk’s being more costly, Google’s not having cost), but would be entirely owned by us and helping with the wider site’s SEO and branding.  Installation needs to be decided, but as Discourse is open source it can be hosted where we determine is best.

**Comment by skippskipp** [comment]
@chrisekelley could you have a look at Mailgun again?
