### ISSUE TITLE
Display error in transition comment

### ISSUE THREAD

**Issue by rjcorwin** [Tangerine-Community/Tangerine-client#147]
Bug introduced in #111 

There is a minor display glitch when you run "EGRA Task 1. Letter Name Knowledge" on subtest "EGRA Task 1. Letter Name Knowledge" - in AssessmentView.handlebars,  {{transitionComment}} should be  {{{transitionComment}}} to avoid html-escaping in handlebars

<img width="682" alt="screen shot 2015-12-16 at 5 08 09 pm" src="https://cloud.githubusercontent.com/assets/861535/11856820/0ebb5f46-a419-11e5-9028-46253c7a256a.png">

**Comment by rjcorwin** [comment]
@chrisekelly In this [new PR](https://github.com/Tangerine-Community/Tangerine-client/pull/146/files#diff-5603cc2763edc17557e484c94f6a7a2aR18) the escaping is working as you recommend but the screenshot you provide brings up potentially another issue. Is the transition comment supposed to only be shown right before the user is to tap the `Next` button? At the moment it is on display immediately upon subtest load which is also on Assessment render.

**Comment by chrisekelley** [comment]
@rjsteinert : I compared the behaviour on the databases.tangerinecentral.org site; it seems to work the same way.
