### ISSUE TITLE
'Resume' should respect the assessment's originally chosen subtest sequence 

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#162]
In the main assessment I'm testing in ("01. LTTP2 2015 - Student"), we have a reading test and a math test, each comprised of several subtests.  The assessment has some "random sequences" assigned to it, you can find these in the assessment editor.  These are set such that some students will be tested in math first, reading second, other students in the reverse order so that we're not always administering in the same order (reduces 'fatigue effect' in the data).  

When I quit an assessment by tapping the Tangerine icon, and then resume it, if I have quit in any of the subtests that may be affected by these "random sequences", I don't reliably "Resume" where I had quit.  That is, if I abort in the assessment's 6th subtest (Phonemic Awareness), I may "Resume" on that one or I may "Resume" on subtest 13 (Quantity Discrimination), because they are both assigned the same position in the 'random sequence' as configured.

This is actually a fairly old bug that @fetmar had resolved at one point.

Testing instructions:
- Tap the play button on the "01. LTTP2 2015 - Student" Assessment.
- Tap your way to the sixth subtest screen. Note the contents of the this screen you will be returning to.
- Tap the orange tangerine in the top left, confirm you want to navigate away.
- Tap the stats button on the "01. LTTP2 2015 - Student" Assessment.
- Scroll all the way down to tap the last "Details" button. 
- Tap the resulting "Resume" button.
- Compare the results of the screen to that from where you left off in this subtest. It should be the same screen.

**Comment by rjcorwin** [comment]
Thanks for the info @skippskipp, that confirms what I was just looking at.
