### ISSUE TITLE
Results sync error

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#188]
Testing on an .apk generated today (Jan.4), I'm getting a persistent error in syncing results:

![screenshot_2016-01-04-13-42-15](https://cloud.githubusercontent.com/assets/2474753/12097696/10d75bdc-b2eb-11e5-8612-88a11154cda5.png)

**Comment by chrisekelley** [comment]
I believe this is a cors issue:

POST http://databases.tangerinecentral.org/_cors_bulk_docs/check/group-sweet_tree 500 (Internal Server Error)

During our server issue yesterday I collected the following:

root@tangerine:~# ps ax|grep ruby
 1622 ?        S      0:00 sudo nohup ruby corsBulkDocs.rb -p 2989
 1623 ?        Sl    35:09 ruby corsBulkDocs.rb -p 2989
 2314 ?        S      0:00 sudo nohup ruby ghost.rb -p 6282
 2315 ?        Sl    18:23 ruby ghost.rb -p 6282
14914 pts/1    S+     0:00 grep --color=auto ruby
29804 ?        Sl   306:15 ruby1.9.1 /usr/local/bin/rackup -p 3141

After we re-booted the server, I don't think we brought everything back up. Looking into this now. We need to get all of these into an init script!

**Comment by chrisekelley** [comment]
/var/www/corsBulkDocs/start.sh starts the corsBulkDocs sinatra app. Results upload fixed.
