### ISSUE TITLE
Upgrade Tanzania group to Tangerine Client 0.1.1

### ISSUE THREAD

**Issue by rjcorwin** [Tangerine-Community/Tangerine-client#199]
Capturing this Server Ops todo in the 0.1.1 milestone for now.

group id on DatabasesTC: group-rti_tanzania_2016

Scott is loading the App onto tablets on Sunday.
## failed plan :P
- [x] Rename `group-rti_tanzania_2016` to `group-rti_tanzania_2016-old`.
- [x] Create a new production CouchDB Database for Tanzania, call it `group-rti_tanzania_2016`.
- [ ] On local laptop, modify the Tangerine Server source code to point to the new Tree server. Use app/_docs/configuration to update the "tree" line.
- [ ] Configure locally the `.couchapprc` file to point to the new Production CouchDB Database, then `couchapp push`.
- [ ] Clone Assessments from `group-rti_tanzania_2016-old` to new Production CouchDB Database `group-rti_tanzania_2016`.
- [ ] Load 0.1.1 release of Tangerine Client onto new Tree server.
- [ ] Mark `group-rti_tanzania_2016-old` for deletion.
- [ ] Download and test APK from Production.

new plan below...
## QA on Test
- [x] Create `test-group-rti_tanzania_2016`
- [x] Replicate `group-rti_tanzania_2016` to `test-group-rti_tanzania_2016`
- [x] On `test-group-rti_tanzania_2016`, modify configuration document so that tree points to the new server (new server address is in Slack personal chat w/ RJ - search for tree; I'll also document it in the wiki) 
- [x] Replicate to group-rti_tanzania_2016_test to adhere to naming convention.
- [x] Load 0.1.1 release of Tangerine Client onto new Tree server.
- [ ] Figure out why users are having permissions issues
- [x] Download and test APK from Production.
- [ ] Perform QA tests.
## Release to Production
- [ ] On `group-rti_tanzania_2016`, modify configuration document so that tree points to the new server (new server address is in Slack personal chat w/ RJ - search for tree; I'll also document it in the wiki) 
- [ ] Download and test APK from Production.
- [ ] Perform QA tests.
### settings to be aware of
- Tree server URL in the Tangerine Server Database, `configuration` document.
- Tablet sync URL in the Tangerine Server Database, `settings` document.

**Comment by rjcorwin** [comment]
Classroom observation Assessment is funky. Has a lot of custom code which we'll need to check if it works with 0.1.1.

**Comment by chrisekelley** [comment]
As a quick test, we may want to copy that one to sweet-tree just to give it a spin. But I'm planning to modify the source that group-rti_tanzania_2016 is using so that it can use the new tree so we can build the apk's directly.

**Comment by rjcorwin** [comment]
+1 for testing the deployment before pushing it to the live instance. I've spent a lot of time working in a dev -> stage -> live workflow. Through my lens, Sweet Tree looks like Dev and every live instance of Tangerine Server needs it's own Staging instance.

**Comment by rjcorwin** [comment]
@chrisekelley I think maybe we should treat group-rti_tanzania_2016 like production given there is ongoing work being done there. I've set up test-group-rti_tanzania_2016 and replicated to it from production. See the `QA on Test` task list above for the next steps. I'll need your help on those.

**Comment by chrisekelley** [comment]
@rjsteinert I believe that on Tangerine server, all couch db names must begin with "group-". I have replicated the "test-group..." couch to group-rti_tanzania_2016-test. Update - underscores, not dashes! Now it is group-rti_tanzania_2016_test

**Comment by chrisekelley** [comment]
I'm updating https://wiki.ictedge.org/display/T/Tangerine+Release+Process while I am working my way through the permissions issues. I am currently unable to create an APK - I am getting the "Sorry, you have to be an admin within the group to make an APK." message. I have opened the tangerine user's _user profile org.couchdb.user:tangerine and add to the list of groups - group-rti_tanzania_2016_test- and opened the couchdb in futon and click security link. Added “tangerine" user to the Admins.

**Comment by chrisekelley** [comment]
Once I added my user to group-rti_tanzania_2016 permissions, it worked! I can now generate an APK. To add other users, open the db in futon, click security, and add them to the Admins or Members. We may have to create an uploader acct for it as well.
