### ISSUE TITLE
Hitting back button in focus mode results in returning to beginning of Assessment

### ISSUE THREAD

**Issue by rjcorwin** [Tangerine-Community/Tangerine-client#226]
@chrisekelley described this to me but I've been unable to reproduce. Creating a ticket for this and assigning to 0.1.3.  I attempted to create an Assessment Pack to test this, ended up finding different issue in this PR https://github.com/Tangerine-Community/Tangerine-client/pull/225

**Comment by chrisekelley** [comment]
Report from Scott this morning: 

> Back button;  confirm/prompt is not happening consistently.  In trying to find a pattern of when it fails, it  seems that it may function initially, but not if that assessment has been resumed.  It also appears to fail if the back button has been pressed more than 4 times in a subtest.  That is, for the first 4 times it’s pressed, the prompt comes.  On the fifth time, pressing the back button kicks the user out of the app completely.  Sometimes it takes fewer than 4 presses to get kicked out.

**Comment by chrisekelley** [comment]
I have confirmed the following: When resuming an assessment and then hitting the back button, the app did not display the prompt. This behavior happens either when I hit Back immediately after resuming or after completing a subtest and then hit Back.

**Comment by chrisekelley** [comment]
I believe this is easy to fix - need to add router.navigateAwayMessage to the resume route.

**Comment by chrisekelley** [comment]
I just committed a fix for this bug in PR #229 
https://github.com/Tangerine-Community/Tangerine-client/pull/229
