### ISSUE TITLE
'Perform another assessment' should not prompt user

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#227]
On the 'Assessment complete' page, once the 'Save result' button is pressed, that button changes into "Perform another assessment", which should start that same assessment from its first subtest (re-launch the same assessment that was just completed), without any prompt. 

Currently, tapping 'Perform another assessment' is giving a prompt:
"Confirm:  Are you sure you wish to quit this assessment?"  

If the user presses "Ok" to this prompt, the assessment re-launches, as it should if the user had just just pressed "Perform another assessment".

**Comment by chrisekelley** [comment]
In ResultItemView.another, need to clear Tangerine.router.navigateAwayMessage so that it is not displayed here.

**Comment by chrisekelley** [comment]
I am keeping some notes on code for detecting back button here: https://gist.github.com/chrisekelley/915063b0d97fdcba8859#file-popstate-md
