### ISSUE TITLE
Error in "Teacher register (P1-P4) and Trainings attended" for Action on display

### ISSUE THREAD

**Issue by chrisekelley** [Tangerine-Community/Tangerine-client#260]
@skip() if ResultOfPrevious("Deputy_exist") isnt "1"

http://databases.tangerinecentral.org/group-fa_tools_2016/_design/ojai/index.html#subtest/8b369ac2-64fc-b8f4-aba7-4bc65c08f644

**Comment by skippskipp** [comment]
This group's editor version had not been updated. Updating seems to have resolved this.
