### ISSUE TITLE
Service monitoring

### ISSUE THREAD

**Issue by fetmar** [Tangerine-Community/Tangerine-client#42]
### Intent

To provide administrators feedback about proper functioning of system components.
### Context

Individual services sometimes run into unexpected problems. In most cases the problems are recovered from automatically and an error messsage is given back to the user. These error messages should be more visible so the problems can be corrected.
### Specifications

Should
- compile brockman, tree, robbert, couchdb, and nginx errors
- display the errors in an easily digestable manner
- display the errors in a way that helps identify options for correction

**Comment by rjcorwin** [comment]
Moved this over to 2.1 Migrate Internal Projects to Dedicated Server because we're preparing a new server and can focus on this during that process.

**Comment by chrisekelley** [comment]
We are using newrelic for the new Tangerine Subscription server(s)
