### ISSUE TITLE
managing configuration

### ISSUE THREAD

**Issue by fetmar** [Tangerine-Community/Tangerine-client#43]
### Intent

To configure only what is necessary for the proper functioning of the system.
### Context

Right now each configuration step is manual and necessary. But there are, in reality, different levels of configuration. Some configuration items may be obtained automatically from a script, others may need to be used several times and would benefit from a system-wide approach.
### Specifications

Should
- provide easy to follow instructions for installing each service.
- provide examples for configurations.
- automatically generate all configuration possible once installed to server.
- "DRY" up configuration

**Comment by chrisekelley** [comment]
We are managing our configuration using Docker.
