### ISSUE TITLE
Android 5 tablet client debug list

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#66]
- 'Clear' button from 'Location' subtest type is functional, but displays 'LocationRunView.button.clear' instead of just label text ('Clear').
- When loading the 'Student Information' subtest (a standard survey subtest), the tablet displayed:
  Alert
  Custom Validation Error
  TypeError:  Cannot read property 'charCodeAt' of undefined.  
  
  This error message persisted twice, pressed 'Ok' each time and then it went away and the survey questions appeared.  The error message then reappeared each time a survey question was answered and also when the 'Next' button was pressed.  
- Could not resume a test.  I generated some initial data, including a student ID, but when pressing the 'Results' button to the right of an instrument's name, I see that there are 2 results.  Tablet reads, "Results (1 - 2 of 2)" but nothing displays below this so there is no option to 'Resume' any result.

**Comment by chrisekelley** [comment]
Clear issue fixed in 47eb9670b087bfc65be3722771c9d007bfb6315d
charCodeAt issue fixed in 7527a37eed2aa51dfe26386c185b258c417a02fb
resume was fixed in 317f05215595e5f8f53e949a2c7fcb0977fc0ca5
