### ISSUE TITLE
client-server sync does not store results

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#67]
Pressing 'Universal Upload' on tablet immediately displays a successful sync message, but online group's results page has none of the data from the client app.

**Comment by chrisekelley** [comment]
Universal Upload is working now - it may have been fixed by commit 86a21a0d92768cbabfc7eeba51d83bbd8908afbc - add utility function to upload compressed data. I'm testing using yesterday's APK.
