### ISSUE TITLE
Setting 'Capture Last Item Attempted' to 'No' prevents grid from displaying

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#71]
Default setting for 'Capture Last Item Attempted' is 'Yes.'  Changing to 'No' will cause a grid test to fail to display.

**Comment by chrisekelley** [comment]
We need to check this one again - I think it may have been fixed.

**Comment by chrisekelley** [comment]
Update from Scott: About #71, Josh had fixed that, yes, but in my testing I found it happening again.  It’s a quirky one if I remember correctly – the grid will not appear at all if it’s the first subtest in an assessment. If it’s the second (or, not the first), the grid will appear, but the button-items won’t display when the timer starts.

**Comment by chrisekelley** [comment]
I just created a test that Default setting for 'Capture Last Item Attempted' is 'No.' It won't even render - for some reason it is not rendering the Yes/No box for Input mode. Note that the version of Tangerine that is on the server is pre-Marionette. I know that Josh has worked on this already, so I'll test it with my code and fix it. 

Here is my test:

http://databases.tangerinecentral.org/group-sweet_tree/_design/ojai/index-dev.html#run/11322a8a-0807-68b6-c469-37ecc571cbf0

**Comment by chrisekelley** [comment]
I installed the a test that Default setting for 'Capture Last Item Attempted' is 'No' on my local instance of Tangerine and the screens render. I also tested it as an apk and it also rendered. But my test may be too simple.

**Comment by skippskipp** [comment]
Seems to be resolved now.
