### ISSUE TITLE
'Skippable' attribute dysfunctional for survey subtest prototype

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#85]
Each subtest prototype has a setting, 'Skippable' ( options of YES / NO).  The default value for this setting is 'NO', meaning that the subtest must be completed before the user can advance.  
- Survey subtests with Skippable == NO, are not currently requiring users to respond to all questions before advancing.  A user can simply press 'Next' to advance to the next subtest.  This appears to only affect tablet apps.

**Comment by chrisekelley** [comment]
I need to get the parent's (SurveyRunItemView) childEvents to listen to the "answer" events spawned by the Questions.

**Comment by chrisekelley** [comment]
Skippable is working now: the user must respond to the required questions. I have run into an issue with getting the value of the dependencies, but am working that out now.
