### ISSUE TITLE
Define tasklist priorities

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#88]
We expect vendor selection by week of 11/23.  Need to identify priority Exec. Function tasks as per field trial needs.  
## Should be agreed upon as close to 11/23 as possible  :calendar:
- Identify and fully detail 2 or 3 of the Exec. Function task templates that will be needed for field trials in January, such that the vendor can prioritize development on these.

**Comment by chrisekelley** [comment]
Vendor selected and EF app implemented
