### ISSUE TITLE
grid scoring and validation errors

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#89]
A few errors in the grid scoring and validation procedures:
- When time expires and the user is promoted to identify the last item read, tapping any grid item does nothing (it neither scores that item nor places the bracket).  It should be that the next item tapped places a red bracket around that item. 
- The user is able to score grid items located after the red bracket.  The user can place the red bracket only by stopping the timer before the allotted time has passed.  This places the red bracket at the final grid item, as it should.  But if the user moves the bracket to any earlier item, the user _**should not**_ be able to score items that are located after the position of the bracket.   This is because the red bracket is used to indicate the last item attempted by the student, so no scoring beyond this item should be allowed.  [This logic must also be carried over to work in the reverse direction for grid subtests which have the 'Right to Left' option set to 'Yes'].  Currently, if the user places the red bracket and then changes the 'Input Mode' to 'Mark', it is possible to score items located after the bracket.

**Comment by chrisekelley** [comment]
I am working on the first error. The app is throwing up a javascript popup alert with the "Please touch last item read." message. When you try to click, no event is triggered. BUT when you click "Next", the last item error message inside the app is displayed (i.e. in html) , and when you click the error, the red brackets are placed around the item. So, I have an idea on how to proceed.

And now I have it sorted. All good.

**Comment by chrisekelley** [comment]
In regards to the second error, I believe my fix for the first error fixes that error too.

**Comment by skippskipp** [comment]
The second error persists.  After time ends, I'm able to tap an item to indicate it was the last attempted.  Then, if I change 'Input Mode' to 'Mark', I'm also able to score items located _after_ the 'last attempted' item.  That shouldn't be possible.
