### ISSUE TITLE
When app starts for the first time, Login screen does not render properly

### ISSUE THREAD

**Issue by chrisekelley** [Tangerine-Community/Tangerine-client#97]
You must refresh to see login

Testing instructions:
- When app starts, log in screen should look as follows in provided screenshot.

<img width="808" alt="screen shot 2015-12-21 at 1 53 47 pm" src="https://cloud.githubusercontent.com/assets/156575/11938669/66565024-a7ea-11e5-83fd-78674ca3d4dd.png">

**Comment by chrisekelley** [comment]
This has been resolved already.

**Comment by skippskipp** [comment]
Something's off in the display, the login is now pegged to the top of the screen on the initial login (it had been centered, ideally should always be centered).  I tried logging in and back out, and would only get this happening every other time or so.  
![screenshot_2015-12-03-15-38-55](https://cloud.githubusercontent.com/assets/2474753/11573493/9fbc8352-99d4-11e5-8c9b-87cb24c7a646.png)

**Comment by chrisekelley** [comment]
Ahh yeah, I think I completely ignored the CSS or html layout for the login page when I brought the code into marionette. I'll revisit this.
